<a href="https://colab.research.google.com/github/delowerhossentuhin/R-Data-Science/blob/main/00_R_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Change Your Runtype python to R**

# **Vector**

In [1]:
num_vec<-c(1,2,3,4,5,6,7)
print(num_vec)

[1] 1 2 3 4 5 6 7


In [2]:
str_vec<-c("Frodo","Sam","Mary","Pippins")
print(str_vec)

[1] "Frodo"   "Sam"     "Mary"    "Pippins"


In [3]:
log_vec<-c(TRUE,FALSE,TRUE)
print(log_vec)

[1]  TRUE FALSE  TRUE


In [4]:
log_vec2<-c(TRUE,FALSE,1,0)
print(log_vec2)

[1] 1 0 1 0


In [5]:
mix_vec = c("Hello",0,TRUE,55.5)
print(mix_vec)

[1] "Hello" "0"     "TRUE"  "55.5" 


In [6]:
print(num_vec[1]) # R language started index is 1 not 0
print(str_vec[3])

[1] 1
[1] "Mary"


In [7]:
num_vec1 = c(1,2,3,4,5,6,7)
num_vec2 =c(2,3,4,5,6,7,8,10)

In [8]:
# Summation
sum_vec=num_vec1+num_vec2
print(sum_vec)
# num_vec2 length > num_vec1 length
# num_vec2's 10 (last index) will be added with num_vec1's first index

Warning message in num_vec1 + num_vec2:
“longer object length is not a multiple of shorter object length”


[1]  3  5  7  9 11 13 15 11


In [9]:
# Subtraction
sub_vec = num_vec1 - num_vec2
print(sub_vec)

Warning message in num_vec1 - num_vec2:
“longer object length is not a multiple of shorter object length”


[1] -1 -1 -1 -1 -1 -1 -1 -9


In [10]:
# Multiplication
mul_vec = sum_vec * sub_vec # Element wise multiplication
print(mul_vec)

[1]  -3  -5  -7  -9 -11 -13 -15 -99


In [11]:
# Division
div_vec = sub_vec / mul_vec
print(div_vec)

[1] 0.33333333 0.20000000 0.14285714 0.11111111 0.09090909 0.07692308 0.06666667
[8] 0.09090909


In [12]:
# appending new element in existing vector
sub_vec <- c(sub_vec,100)
print(sub_vec)

[1]  -1  -1  -1  -1  -1  -1  -1  -9 100


In [13]:
sub_vec[3]=100
print(sub_vec)

[1]  -1  -1 100  -1  -1  -1  -1  -9 100


In [14]:
sub_vec <- c(num_vec1[num_vec1 %%2==0], sub_vec)
print(sub_vec)

 [1]   2   4   6  -1  -1 100  -1  -1  -1  -1  -9 100


In [15]:
# Vector Function
print(length(sub_vec))
print(mean(sub_vec))
print(sum(sub_vec))
sub_vec <- sort(sub_vec,decreasing = TRUE)
print(sub_vec)

[1] 12
[1] 16.41667
[1] 197
 [1] 100 100   6   4   2  -1  -1  -1  -1  -1  -1  -9


In [16]:
# Sequence and Repetition in Vectors
seq_vec = seq(3,100,10)
print(seq_vec)
rep_vec <- rep(seq(0,10,2),time=3)
print(rep_vec)

 [1]  3 13 23 33 43 53 63 73 83 93
 [1]  0  2  4  6  8 10  0  2  4  6  8 10  0  2  4  6  8 10


# **Matrix**

In [17]:
# Creating a 3x3 matrix (filled column-wise by default)
mat1=matrix(1:9, nrow=3,ncol=3)
print(mat1)
cat("\n\n")
mat2=matrix(1:12,nrow=4,ncol=3, byrow = TRUE) # filled row wise
print(mat2)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [18]:
# Naming Rows and Columns
rownames(mat2) = c("A","B","C","D") # length must be same as the number of rows
print(mat2)
cat("\n\n")
colnames(mat2) = c("X","Y","Z")
print(mat2)

  [,1] [,2] [,3]
A    1    2    3
B    4    5    6
C    7    8    9
D   10   11   12


   X  Y  Z
A  1  2  3
B  4  5  6
C  7  8  9
D 10 11 12


In [19]:
# Accessing Elements in a Matrix
print(mat2[2,3])
print(mat2[,2]) # 2nd entire column
print(mat2[3,]) # 3 entire row

[1] 6
 A  B  C  D 
 2  5  8 11 
X Y Z 
7 8 9 


In [20]:
# Matrix Arithmetic
mat1 <- matrix(1:4, nrow = 2)
mat2 <- matrix(5:8, nrow = 2)

# Matrix addition
sum_mat <- mat1 + mat2
print(sum_mat)

# Matrix multiplication (element-wise)
prod_mat <- mat1 * mat2
print(prod_mat)

dot_prod = mat1 %*% mat2
print(dot_prod)

     [,1] [,2]
[1,]    6   10
[2,]    8   12
     [,1] [,2]
[1,]    5   21
[2,]   12   32
     [,1] [,2]
[1,]   23   31
[2,]   34   46


In [21]:
#Transpose and Inverse of a Matrix
# Transpose of a matrix
t_mat <- t(mat1)
print(t_mat)

# Inverse of a matrix (for square matrices)
square_mat <- matrix(c(2, 3, 1, 4), nrow = 2)
print(square_mat)
inv_mat <- solve(square_mat)
print(inv_mat)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
     [,1] [,2]
[1,]    2    1
[2,]    3    4
     [,1] [,2]
[1,]  0.8 -0.2
[2,] -0.6  0.4


### **Array**

In [22]:
arr1 <- array(1:18, dim=c(3,3,2))
print(arr1)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18



In [23]:
print(arr1[2,3,1])
print(arr1[,3,2]) # 3rd column from 2nd layer
print(arr1[2,,1]) # 2nd row from 1st layer

[1] 8
[1] 16 17 18
[1] 2 5 8


In [24]:
arr2 <- array(19:36, dim = c(3, 3, 2))
print(arr2+arr1)

, , 1

     [,1] [,2] [,3]
[1,]   20   26   32
[2,]   22   28   34
[3,]   24   30   36

, , 2

     [,1] [,2] [,3]
[1,]   38   44   50
[2,]   40   46   52
[3,]   42   48   54



In [25]:
# Element-wise multiplication
prod_arr <- arr1 * arr2
print(prod_arr)

, , 1

     [,1] [,2] [,3]
[1,]   19   88  175
[2,]   40  115  208
[3,]   63  144  243

, , 2

     [,1] [,2] [,3]
[1,]  280  403  544
[2,]  319  448  595
[3,]  360  495  648



In [26]:
print(sum(arr1)) # Sum of all elements in the array
print(mean(arr1)) # Mean of all elements
apply(arr1, MARGIN = 1, FUN = sum) # margin 1 means Row
apply(arr1, MARGIN = 2, FUN = prod) # margin 2 means Column

[1] 171
[1] 9.5


[1] 51 57 63

[1]    7920  327600 2467584

# **Data Frame**

In [27]:
# Creating a simple data frame
df <- data.frame(
  ID = c(101, 102, 103, 104),
  Name = c("Alice", "Bob", "Charlie", "David"), # Name is Column
  Age = c(23, 25, 22, 24),
  Score = c(89.5, 76.0, 91.2, 88.8), # Every Column have to be same number of elements
  Passed = c(TRUE, FALSE, TRUE, TRUE)
)
print(df)

   ID    Name Age Score Passed
1 101   Alice  23  89.5   TRUE
2 102     Bob  25  76.0  FALSE
3 103 Charlie  22  91.2   TRUE
4 104   David  24  88.8   TRUE


In [28]:
print(df $ Name) # Accessing a Single Column
print(df[,2]) # Accessing a Single Column
print(df[1,]) # Accessing a Single Row
print(df[,"Age"])
print(df[2,"Score"])
print(df[1:3,"Age"]) # Accessing Multiple Row

[1] "Alice"   "Bob"     "Charlie" "David"  
[1] "Alice"   "Bob"     "Charlie" "David"  
   ID  Name Age Score Passed
1 101 Alice  23  89.5   TRUE
[1] 23 25 22 24
[1] 76
[1] 23 25 22


In [29]:
df$Grade <- c("A", "B", "A+", "A-") # Add a new column 'Grade'

print(df)

   ID    Name Age Score Passed Grade
1 101   Alice  23  89.5   TRUE     A
2 102     Bob  25  76.0  FALSE     B
3 103 Charlie  22  91.2   TRUE    A+
4 104   David  24  88.8   TRUE    A-


In [30]:
Passed_Std <- df[df$Passed == TRUE,]
print(Passed_Std)

   ID    Name Age Score Passed Grade
1 101   Alice  23  89.5   TRUE     A
3 103 Charlie  22  91.2   TRUE    A+
4 104   David  24  88.8   TRUE    A-


In [31]:
high <- df[df$Score > 85,]
print(high)

   ID    Name Age Score Passed Grade
1 101   Alice  23  89.5   TRUE     A
3 103 Charlie  22  91.2   TRUE    A+
4 104   David  24  88.8   TRUE    A-


In [32]:
df_sort <- df[order(df$Score,decreasing = TRUE),] # Sorted row based on a specific Column
print(df_sort)

   ID    Name Age Score Passed Grade
3 103 Charlie  22  91.2   TRUE    A+
1 101   Alice  23  89.5   TRUE     A
4 104   David  24  88.8   TRUE    A-
2 102     Bob  25  76.0  FALSE     B


In [33]:
df$Score[df$Name == "Bob"] <- 80
print(df)

   ID    Name Age Score Passed Grade
1 101   Alice  23  89.5   TRUE     A
2 102     Bob  25  80.0  FALSE     B
3 103 Charlie  22  91.2   TRUE    A+
4 104   David  24  88.8   TRUE    A-


In [34]:
df$Passed[df$Score<95] <- FALSE
print(df)

   ID    Name Age Score Passed Grade
1 101   Alice  23  89.5  FALSE     A
2 102     Bob  25  80.0  FALSE     B
3 103 Charlie  22  91.2  FALSE    A+
4 104   David  24  88.8  FALSE    A-


In [35]:
colnames(df) <- c("Student_ID", "Student_Name", "Student_Age", "Exam_Score", "Passed_Exam", "Final_Grade")
df

Student_ID Student_Name Student_Age Exam_Score Passed_Exam Final_Grade
1 101        Alice        23          89.5       FALSE       A          
2 102        Bob          25          80.0       FALSE       B          
3 103        Charlie      22          91.2       FALSE       A+         
4 104        David        24          88.8       FALSE       A-

In [36]:
df$Final_Grade <- NULL # Removing a Column
print(df)

  Student_ID Student_Name Student_Age Exam_Score Passed_Exam
1        101        Alice          23       89.5       FALSE
2        102          Bob          25       80.0       FALSE
3        103      Charlie          22       91.2       FALSE
4        104        David          24       88.8       FALSE


In [37]:
df <- df[-2,] # Remove 2nd Row
df

Student_ID Student_Name Student_Age Exam_Score Passed_Exam
1 101        Alice        23          89.5       FALSE      
3 103        Charlie      22          91.2       FALSE      
4 104        David        24          88.8       FALSE

In [38]:
summary(df) # Get summary statistics
str(df) # Get structure of the data frame

   Student_ID    Student_Name        Student_Age     Exam_Score   
 Min.   :101.0   Length:3           Min.   :22.0   Min.   :88.80  
 1st Qu.:102.0   Class :character   1st Qu.:22.5   1st Qu.:89.15  
 Median :103.0   Mode  :character   Median :23.0   Median :89.50  
 Mean   :102.7                      Mean   :23.0   Mean   :89.83  
 3rd Qu.:103.5                      3rd Qu.:23.5   3rd Qu.:90.35  
 Max.   :104.0                      Max.   :24.0   Max.   :91.20  
 Passed_Exam    
 Mode :logical  
 FALSE:3        
                
                
                
                

'data.frame':	3 obs. of  5 variables:
 $ Student_ID  : num  101 103 104
 $ Student_Name: chr  "Alice" "Charlie" "David"
 $ Student_Age : num  23 22 24
 $ Exam_Score  : num  89.5 91.2 88.8
 $ Passed_Exam : logi  FALSE FALSE FALSE


# **Key Differences Between data.frame and list in R:**

| Feature              | `list`                                                   | `data.frame`                                    |
| -------------------- | -------------------------------------------------------- | ----------------------------------------------- |
| **Structure**        | General-purpose container                                | Special type of list with tabular format        |
| **Dimensions**       | 1D (a list of elements)                                  | 2D (rows × columns)                             |
| **Element Types**    | Can store any type, each element can be different length | Each column is a vector (same length)           |
| **Element Access**   | Access with `[[ ]]` or `$`                               | Same, but can also use `[ , ]` for rows/columns |
| **Tabular Data Use** | Not intended for tables                                  | Designed for tabular (spreadsheet-like) data    |
| **Column Lengths**   | Can be different                                         | All columns must have the same number of rows   |
| **Printing**         | Prints as a nested structure                             | Prints as a neat table                          |


# **List**

In [39]:
my_list <- list(
  Name = "Alice",
  Age = 25,         # Creating a list with different data types
  Scores = c(90, 85, 88),
  Passed = TRUE
)
print(my_list)

$Name
[1] "Alice"

$Age
[1] 25

$Scores
[1] 90 85 88

$Passed
[1] TRUE



In [40]:
print(my_list[1])
print(my_list$Scores)
print(my_list[3])
print(my_list[[3]][2])
print(my_list$Scores[2])

$Name
[1] "Alice"

[1] 90 85 88
$Scores
[1] 90 85 88

[1] 85
[1] 85


In [41]:
my_list$Age <- 22
print(my_list$Age) # Change The Value
my_list$Scores <- c(my_list$Scores,100)
print(my_list$Scores)
my_list$country <- "USA" # Add new element
print(my_list$country)
my_list$country <- c(my_list$country,"UK","Japan")
print(my_list$country)

[1] 22
[1]  90  85  88 100
[1] "USA"
[1] "USA"   "UK"    "Japan"


In [42]:
my_list$Passed <- NULL
print(my_list)

$Name
[1] "Alice"

$Age
[1] 22

$Scores
[1]  90  85  88 100

$country
[1] "USA"   "UK"    "Japan"



In [43]:
comp_list=list(    # A list with Vector, Array, Matrix, DataFrame
  arr1 = array(1:18, dim=c(3,3,2)),
  number=rep(seq(1,10,3),2),
  matr = matrix(rep(seq(1, 17, 2),2), nrow = 3),
  dafr = data.frame(
    Name=c("John","Sansa","Robert","Joffery","Theon"),
    Value=c(FALSE,TRUE,FALSE,FALSE,TRUE)
  )
)
print(comp_list)

$arr1
, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18


$number
[1]  1  4  7 10  1  4  7 10

$matr
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    7   13    1    7   13
[2,]    3    9   15    3    9   15
[3,]    5   11   17    5   11   17

$dafr
     Name Value
1    John FALSE
2   Sansa  TRUE
3  Robert FALSE
4 Joffery FALSE
5   Theon  TRUE



In [44]:
print(comp_list$matr)
print(comp_list$matr[2,3])

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    7   13    1    7   13
[2,]    3    9   15    3    9   15
[3,]    5   11   17    5   11   17
[1] 15


In [45]:
print(comp_list$dafr$Name)

[1] "John"    "Sansa"   "Robert"  "Joffery" "Theon"  


In [46]:
list1 <- list(A = 1:5, B = "Hello")
list2 <- list(C = c(TRUE, FALSE), D = matrix(1:4, nrow = 2))
merged_list <- c(list1, list2) # Merge lists
print(merged_list)

$A
[1] 1 2 3 4 5

$B
[1] "Hello"

$C
[1]  TRUE FALSE

$D
     [,1] [,2]
[1,]    1    3
[2,]    2    4

