<a href="https://colab.research.google.com/github/delowerhossentuhin/R-Data-Science/blob/main/00_R_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Change Your Runtype python to R**

# **Vector**

In [1]:
num_vec<-c(1,2,3,4,5,6,7)
print(num_vec)

[1] 1 2 3 4 5 6 7


In [2]:
str_vec<-c("Frodo","Sam","Mary","Pippins")
print(str_vec)

[1] "Frodo"   "Sam"     "Mary"    "Pippins"


In [3]:
log_vec<-c(TRUE,FALSE,TRUE)
print(log_vec)

[1]  TRUE FALSE  TRUE


In [4]:
log_vec2<-c(TRUE,FALSE,1,0)
print(log_vec2)

[1] 1 0 1 0


In [5]:
mix_vec = c("Hello",0,TRUE,55.5)
print(mix_vec)

[1] "Hello" "0"     "TRUE"  "55.5" 


In [6]:
print(num_vec[1]) # R language started index is 1 not 0
print(str_vec[3])

[1] 1
[1] "Mary"


In [7]:
num_vec1 = c(1,2,3,4,5,6,7)
num_vec2 =c(2,3,4,5,6,7,8,10)

In [8]:
# Summation
sum_vec=num_vec1+num_vec2
print(sum_vec)
# num_vec2 length > num_vec1 length
# num_vec2's 10 (last index) will be added with num_vec1's first index

Warning message in num_vec1 + num_vec2:
“longer object length is not a multiple of shorter object length”


[1]  3  5  7  9 11 13 15 11


In [9]:
# Subtraction
sub_vec = num_vec1 - num_vec2
print(sub_vec)

Warning message in num_vec1 - num_vec2:
“longer object length is not a multiple of shorter object length”


[1] -1 -1 -1 -1 -1 -1 -1 -9


In [10]:
# Multiplication
mul_vec = sum_vec * sub_vec # Element wise multiplication
print(mul_vec)

[1]  -3  -5  -7  -9 -11 -13 -15 -99


In [11]:
# Division
div_vec = sub_vec / mul_vec
print(div_vec)

[1] 0.33333333 0.20000000 0.14285714 0.11111111 0.09090909 0.07692308 0.06666667
[8] 0.09090909


In [12]:
# appending new element in existing vector
sub_vec <- c(sub_vec,100)
print(sub_vec)

[1]  -1  -1  -1  -1  -1  -1  -1  -9 100


In [13]:
sub_vec[3]=100
print(sub_vec)

[1]  -1  -1 100  -1  -1  -1  -1  -9 100


In [14]:
sub_vec <- c(num_vec1[num_vec1 %%2==0], sub_vec)
print(sub_vec)

 [1]   2   4   6  -1  -1 100  -1  -1  -1  -1  -9 100


In [15]:
# Vector Function
print(length(sub_vec))
print(mean(sub_vec))
print(sum(sub_vec))
sub_vec <- sort(sub_vec,decreasing = TRUE)
print(sub_vec)

[1] 12
[1] 16.41667
[1] 197
 [1] 100 100   6   4   2  -1  -1  -1  -1  -1  -1  -9


In [16]:
# Sequence and Repetition in Vectors
seq_vec = seq(3,100,10)
print(seq_vec)
rep_vec <- rep(seq(0,10,2),time=3)
print(rep_vec)

 [1]  3 13 23 33 43 53 63 73 83 93
 [1]  0  2  4  6  8 10  0  2  4  6  8 10  0  2  4  6  8 10


# **Matrix**

In [17]:
# Creating a 3x3 matrix (filled column-wise by default)
mat1=matrix(1:9, nrow=3,ncol=3)
print(mat1)
cat("\n\n")
mat2=matrix(1:12,nrow=4,ncol=3, byrow = TRUE) # filled row wise
print(mat2)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [18]:
# Naming Rows and Columns
rownames(mat2) = c("A","B","C","D") # length must be same as the number of rows
print(mat2)
cat("\n\n")
colnames(mat2) = c("X","Y","Z")
print(mat2)

  [,1] [,2] [,3]
A    1    2    3
B    4    5    6
C    7    8    9
D   10   11   12


   X  Y  Z
A  1  2  3
B  4  5  6
C  7  8  9
D 10 11 12


In [19]:
# Accessing Elements in a Matrix
print(mat2[2,3])
print(mat2[,2]) # 2nd entire column
print(mat2[3,]) # 3 entire row

[1] 6
 A  B  C  D 
 2  5  8 11 
X Y Z 
7 8 9 


In [20]:
# Matrix Arithmetic
mat1 <- matrix(1:4, nrow = 2)
mat2 <- matrix(5:8, nrow = 2)

# Matrix addition
sum_mat <- mat1 + mat2
print(sum_mat)

# Matrix multiplication (element-wise)
prod_mat <- mat1 * mat2
print(prod_mat)

dot_prod = mat1 %*% mat2
print(dot_prod)

     [,1] [,2]
[1,]    6   10
[2,]    8   12
     [,1] [,2]
[1,]    5   21
[2,]   12   32
     [,1] [,2]
[1,]   23   31
[2,]   34   46


In [21]:
#Transpose and Inverse of a Matrix
# Transpose of a matrix
t_mat <- t(mat1)
print(t_mat)

# Inverse of a matrix (for square matrices)
square_mat <- matrix(c(2, 3, 1, 4), nrow = 2)
print(square_mat)
inv_mat <- solve(square_mat)
print(inv_mat)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
     [,1] [,2]
[1,]    2    1
[2,]    3    4
     [,1] [,2]
[1,]  0.8 -0.2
[2,] -0.6  0.4
